### 1.1.3.20. Matrix Kronecker Product

$$
\mathbf{A} \otimes \mathbf{B} =
\begin{bmatrix}
A_{11}\mathbf{B} & \cdots & A_{1n}\mathbf{B} \\
\vdots & \ddots & \vdots \\
A_{m1}\mathbf{B} & \cdots & A_{mn}\mathbf{B}
\end{bmatrix}
$$

**Explanation:**

The Kronecker product of matrices $\mathbf{A} \in \mathbb{R}^{m \times n}$ and $\mathbf{B} \in \mathbb{R}^{p \times q}$ is the block matrix resulting in size $(mp) \times (nq)$.

**Properties:**
- $(\mathbf{A} \otimes \mathbf{B})(\mathbf{C} \otimes \mathbf{D}) = (\mathbf{AC}) \otimes (\mathbf{BD})$, when the products are defined
- $(\mathbf{A} \otimes \mathbf{B})^T = \mathbf{A}^T \otimes \mathbf{B}^T$
- Useful in tensor algebra, signal processing, and control

Benefits from the block viewpoint in [Matrix Block Multiplication](./19_matrix_block_multiplication.ipynb) and the compatibility rules in [Matrix Multiplication](./05_matrix_multiplication.ipynb). The rank-one special case is closely related to the [Matrix Outer Product](./14_matrix_outer_product.ipynb).

**Example:**

Let

$$
\mathbf{A} =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\quad
\mathbf{B} =
\begin{bmatrix}
0 & 5 \\
6 & 7
\end{bmatrix}.
$$

Then

$$
\mathbf{A} \otimes \mathbf{B} =
\begin{bmatrix}
0 & 5 & 0 & 10 \\
6 & 7 & 12 & 14 \\
0 & 15 & 0 & 20 \\
18 & 21 & 24 & 28
\end{bmatrix}.
$$


In [1]:
import numpy as np

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[0, 5], [6, 7]])

kronecker_product = np.kron(matrix_a, matrix_b)

print("A ⊗ B =\n", kronecker_product)

A ⊗ B =
 [[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


**References:**

[📘 Aazi, M. (2024). *Mathematics For Machine Learning*](https://www.scribd.com/document/812294393/Mathematics-for-Machine-Learning)  

---

[⬅️ Previous: Block Matrix Multiplication](./19_matrix_block_multiplication.ipynb) | [Next: Augmented Matrix ➡️](../04_Computational_Linear_Algebra/01_augmented_matrix.ipynb)
